language: node_js
notifications:
  email:
  - bitcodin-node@bitmovin.net
before_install:
- openssl aes-256-cbc -K $encrypted_72ad2aca5717_key -iv $encrypted_72ad2aca5717_iv
  -in test/resources/settings.json.enc -out test/resources/settings.json -d
